---
- hosts: docker_vm
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml

    - name: Update all apt packages
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      when: ansible_facts.os_family == "Debian"

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
      when: ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Setup Portainer.
      ansible.builtin.import_tasks: tasks/portainer.yml
      when: portainer_enable

    - name: Setup Jenkins.
      ansible.builtin.import_tasks: tasks/jenkins.yml
      when: jenkins_enable
    
    - name: Setup Bitbucket.
      ansible.builtin.import_tasks: tasks/bitbucket.yml
      when: bitbucket_enable

    - name: Set up Pi Hole.
      ansible.builtin.import_tasks: tasks/pi-hole.yml
      when: pihole_enable
    
    - name: Set up Sonarr.
      ansible.builtin.import_tasks: tasks/sonarr.yml
      when: sonarr_enable