---
- name: Create bitbucket folder on host.
  ansible.builtin.file:
    path: "{{ config_dir }}/bitbucket"
    state: directory
    mode: 0755
  become: false

- name: Copy jenkins docker compose on host.
  ansible.builtin.template:
    src: templates/bitbucket-docker-compose.yml.j2
    dest: "{{ config_dir }}/bitbucket/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart bitbucket

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure bitbucket is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/bitbucket/"
    build: false
  become: false